#print("Hello World")
#print("Mary's cosmetics")
#print('신씨가 소리를 질렀다. "도둑이야."')
#print("C:\\Windows")
#print("안녕하세요.\n만나서\t\t반갑습니다.")
#print("오늘은", "일요일")
#print("naver", "kakao", "sk", "samsung", sep=';')
#print("naver", "kakao", "sk", "samsung", sep='/')
#print("first", end="");print("second")
#print(5/3)
